version: '3.7'
services:
  mysql:
    image: mysql
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=java47
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql 
      - ./infra/backup_dump.sql:/docker-entrypoint-initdb.d/my_dump.sql
  mongodb: 
    image: mongo  
    container_name: mongodbFintech
    ports:
      - 27017:27017 
    command: mongod --noauth
    environment:
      MONGO_INITDB_DATABASE: fintechUsers
    volumes:
      - mongofintech_volume:/data/db 
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - MAVEN_OPTS=-DskipTests
    ports:
      - 8080:8080
    command: ["./mvnw", "spring-boot:run"]
    environment:
      SPRING_DATA_MONGODB_URI:  mongodb://mongodb:27017/fintechUsers
      TZ: UTC
    volumes:
      - .:/opt/app
    depends_on:
      - mysql
  dump-exporter:
    container_name: mysqldump
    build:
      context: .
      dockerfile: Dockerfile_mysqlDump
    volumes:
      - ./dump.sql:/dump.sql
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: java47
    depends_on:
      - mysql
    restart: always
volumes:
  mysql:
  mongofintech_volume: 