version: '3.7'
services:
  mysql:
    image: mysql
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=java47
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql 
      - ./infra/dump.sql:/docker-entrypoint-initdb.d/dump.sql
  mongodb: 
    image: mongo  
    container_name: mongodb
    ports:
      - 27017:27017 
    environment:
      MONGO_INITDB_ROOT_USERNAME: sergey
      MONGO_INITDB_ROOT_PASSWORD: masterkey
      MONGO_INITDB_DATABASE: fintechUsers
    volumes:
      - mongo_volume:/data/db 
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - MAVEN_OPTS=-DskipTests
    ports:
      - 8080:8080
    # command: ["./mvnw", "spring-boot:run"]
    environment:
      SPRING_DATA_MONGODB_URI:  mongodb://sergey:masterkey@mongodb:27017/fintechUsers
    volumes:
      - .:/opt/app
    depends_on:
      - mysql
volumes:
  mysql:
  mongo_volume: 